# week09/example-3/k8s/order-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w09-aks
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: 'true'   # Prometheus scrapes this pod
        prometheus.io/path: '/metrics' # Metrics endpoint
        prometheus.io/port: '8000'     # Metrics port
    spec:
      containers:
      - name: order-service-container
        image: munaweek09acr.azurecr.io/order-service:latest   # ✅ fixed ACR image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000                                   # ✅ match app port
        env:
        - name: POSTGRES_HOST
          value: order-db-service-w09-aks
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w09-aks
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w09-aks
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w09-aks
              key: POSTGRES_PASSWORD
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w09-aks
              key: PRODUCT_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-w09-aks
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001       # exposed to outside
      targetPort: 8000 # forwarded to container port
  type: LoadBalancer
